// demos/vue/src/App.vue
<script setup lang="ts">
import { computed } from 'vue'
import TaskColumn from './components/TaskColumn.vue'
import { useTaskStore } from './stores/tasks'
import type { Column } from './types'

const store        = useTaskStore()
const portfolioUrl = '/'

const columns: Column[] = [
  { id: 'todo', label: 'To Do', color: '#64748b', accent: 'rgba(100, 116, 139, 0.15)' },
  { id: 'in-progress', label: 'In Progress', color: '#f59e0b', accent: 'rgba(245, 158, 11, 0.12)' },
  { id: 'done', label: 'Done', color: '#22c55e', accent: 'rgba(34, 197, 94, 0.12)' },
]

const progress = computed(() => {
  const total = store.tasks.length
  const done = store.totalByStatus.done
  return total > 0 ? Math.round((done / total) * 100) : 0
})
</script>

<template>
  <div class="app">
    <!-- Top bar -->
    <div class="topbar">
      <a :href="portfolioUrl" class="back-link">← Portfolio</a>
      <div class="topbar-center">
        <span class="tech-badge vue">Vue 3</span>
        <span class="tech-badge ts">TypeScript</span>
        <span class="tech-badge pinia">Pinia</span>
      </div>
      <div class="topbar-right" />
    </div>

    <div class="container">
      <!-- Header -->
      <div class="board-header">
        <div>
          <h1 class="board-title">Task Board</h1>
          <p class="board-subtitle">
            Built with Vue 3 Composition API, Pinia, and TypeScript
          </p>
        </div>
        <div class="board-stats">
          <div class="progress-bar-wrap">
            <div class="progress-label">
              <span>Progress</span>
              <span class="progress-value">{{ progress }}%</span>
            </div>
            <div class="progress-track">
              <div class="progress-fill" :style="{ width: progress + '%' }" />
            </div>
          </div>
          <div class="stat-pills">
            <span class="stat-pill todo">{{ store.totalByStatus.todo }} todo</span>
            <span class="stat-pill wip">{{ store.totalByStatus['in-progress'] }} active</span>
            <span class="stat-pill done">{{ store.totalByStatus.done }} done</span>
          </div>
        </div>
      </div>

      <!-- Filters -->
      <div class="filters">
        <input
          v-model="store.searchQuery"
          class="search-input"
          placeholder="Search tasks..."
        />
        <select v-model="store.filterPriority" class="filter-select">
          <option value="all">All priorities</option>
          <option value="high">High priority</option>
          <option value="medium">Medium priority</option>
          <option value="low">Low priority</option>
        </select>
      </div>

      <!-- Board -->
      <div class="board">
        <TaskColumn
          v-for="col in columns"
          :key="col.id"
          :id="col.id"
          :label="col.label"
          :color="col.color"
          :tasks="store.tasksByStatus(col.id)"
        />
      </div>

      <!-- Code callout -->
      <div class="code-callout">
        <div class="code-callout-title">What this demo shows</div>
        <div class="code-callout-items">
          <div class="code-item">
            <span class="code-item-icon">🧩</span>
            <span><strong>Composition API</strong> — <code>&lt;script setup&gt;</code>, <code>ref</code>, <code>computed</code></span>
          </div>
          <div class="code-item">
            <span class="code-item-icon">🗃️</span>
            <span><strong>Pinia</strong> — defineStore with composable-style setup</span>
          </div>
          <div class="code-item">
            <span class="code-item-icon">🔷</span>
            <span><strong>TypeScript</strong> — typed props, store, computed values</span>
          </div>
          <div class="code-item">
            <span class="code-item-icon">✨</span>
            <span><strong>Transitions</strong> — TransitionGroup for smooth card animations</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style>
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
html, body { background: #060610; color: #e2e8f0; font-family: 'Inter', sans-serif; min-height: 100vh; }
</style>

<style scoped>
.app { min-height: 100vh; display: flex; flex-direction: column; }

.topbar {
  background: rgba(6, 6, 16, 0.9);
  backdrop-filter: blur(10px);
  border-bottom: 1px solid rgba(255,255,255,0.06);
  padding: 12px 24px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  position: sticky;
  top: 0;
  z-index: 100;
}

.back-link {
  font-size: 13px;
  color: #64748b;
  text-decoration: none;
  font-weight: 500;
  transition: color 0.15s;
}
.back-link:hover { color: #e2e8f0; }

.topbar-center {
  display: flex;
  gap: 8px;
}

.topbar-right { width: 80px; }

.tech-badge {
  padding: 4px 10px;
  border-radius: 6px;
  font-size: 12px;
  font-weight: 600;
}
.tech-badge.vue {
  background: rgba(66, 184, 131, 0.12);
  border: 1px solid rgba(66, 184, 131, 0.25);
  color: #42b883;
}
.tech-badge.ts {
  background: rgba(49, 120, 198, 0.12);
  border: 1px solid rgba(49, 120, 198, 0.25);
  color: #3b82f6;
}
.tech-badge.pinia {
  background: rgba(255, 198, 41, 0.1);
  border: 1px solid rgba(255, 198, 41, 0.2);
  color: #ffc629;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 40px 24px 60px;
  width: 100%;
  flex: 1;
}

.board-header {
  display: flex;
  align-items: flex-start;
  justify-content: space-between;
  gap: 24px;
  margin-bottom: 28px;
  flex-wrap: wrap;
}

.board-title {
  font-size: 28px;
  font-weight: 800;
  letter-spacing: -0.03em;
  color: #fff;
  margin-bottom: 6px;
}

.board-subtitle {
  font-size: 14px;
  color: #64748b;
}

.board-stats {
  display: flex;
  flex-direction: column;
  gap: 10px;
  min-width: 200px;
}

.progress-label {
  display: flex;
  justify-content: space-between;
  font-size: 12px;
  color: #64748b;
  margin-bottom: 6px;
}

.progress-value { color: #22c55e; font-weight: 600; }

.progress-track {
  height: 4px;
  background: rgba(255,255,255,0.06);
  border-radius: 2px;
  overflow: hidden;
}

.progress-fill {
  height: 100%;
  background: linear-gradient(90deg, #22c55e, #16a34a);
  border-radius: 2px;
  transition: width 0.5s ease;
}

.stat-pills { display: flex; gap: 6px; flex-wrap: wrap; }

.stat-pill {
  padding: 3px 10px;
  border-radius: 100px;
  font-size: 11px;
  font-weight: 600;
}
.stat-pill.todo { background: rgba(100,116,139,0.12); color: #94a3b8; }
.stat-pill.wip { background: rgba(245,158,11,0.1); color: #f59e0b; }
.stat-pill.done { background: rgba(34,197,94,0.1); color: #22c55e; }

.filters {
  display: flex;
  gap: 12px;
  margin-bottom: 24px;
  flex-wrap: wrap;
}

.search-input, .filter-select {
  background: #0d0d1a;
  border: 1px solid rgba(255,255,255,0.08);
  border-radius: 8px;
  padding: 10px 14px;
  font-size: 13px;
  color: #e2e8f0;
  font-family: inherit;
  outline: none;
  transition: border-color 0.15s;
}

.search-input { flex: 1; min-width: 200px; }
.search-input:focus, .filter-select:focus { border-color: rgba(99,102,241,0.4); }
.filter-select { cursor: pointer; }
.filter-select option { background: #0d0d1a; }

.board {
  display: flex;
  gap: 16px;
  align-items: flex-start;
  overflow-x: auto;
  padding-bottom: 8px;
}

.code-callout {
  margin-top: 40px;
  background: #0a0a18;
  border: 1px solid rgba(99, 102, 241, 0.15);
  border-radius: 12px;
  padding: 24px;
}

.code-callout-title {
  font-size: 13px;
  font-weight: 600;
  color: #818cf8;
  margin-bottom: 16px;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

.code-callout-items {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));
  gap: 12px;
}

.code-item {
  display: flex;
  align-items: flex-start;
  gap: 10px;
  font-size: 13px;
  color: #64748b;
  line-height: 1.5;
}

.code-item strong { color: #94a3b8; }
.code-item code {
  background: rgba(99, 102, 241, 0.1);
  border-radius: 4px;
  padding: 1px 5px;
  font-size: 12px;
  color: #818cf8;
  font-family: monospace;
}

.code-item-icon { font-size: 16px; flex-shrink: 0; }
</style>

// demos/svelte/src/App.svelte
<script lang="ts">
  import { writable, derived } from 'svelte/store'
  import { fade, fly, slide } from 'svelte/transition'
  import { flip } from 'svelte/animate'

  const portfolioUrl = '/'

  // ── Svelte store ────────────────────────────────────────────────────────────
  interface Task { id: number; title: string; done: boolean; priority: 'low' | 'medium' | 'high' }

  const tasks = writable<Task[]>([
    { id: 1, title: 'Learn Svelte stores',    done: true,  priority: 'high' },
    { id: 2, title: 'Build reactive UI',       done: true,  priority: 'high' },
    { id: 3, title: 'Use Svelte transitions',  done: false, priority: 'medium' },
    { id: 4, title: 'Animate with flip()',     done: false, priority: 'medium' },
    { id: 5, title: 'Deploy with Vite',        done: false, priority: 'low' },
  ])

  // Derived store — reaktiv beräkning
  const stats = derived(tasks, $tasks => ({
    total:    $tasks.length,
    done:     $tasks.filter(t => t.done).length,
    active:   $tasks.filter(t => !t.done).length,
    progress: $tasks.length ? Math.round($tasks.filter(t => t.done).length / $tasks.length * 100) : 0,
  }))

  // ── Reaktiv deklaration ($:) ─────────────────────────────────────────────
  let filterDone = false
  $: filtered = filterDone ? $tasks.filter(t => !t.done) : $tasks

  let newTitle = ''
  let nextId = 6

  function addTask() {
    if (!newTitle.trim()) return
    tasks.update(ts => [...ts, { id: nextId++, title: newTitle.trim(), done: false, priority: 'medium' }])
    newTitle = ''
  }

  function toggle(id: number) {
    tasks.update(ts => ts.map(t => t.id === id ? { ...t, done: !t.done } : t))
  }

  function remove(id: number) {
    tasks.update(ts => ts.filter(t => t.id !== id))
  }

  const priorityColor: Record<string, string> = {
    high: '#ef4444', medium: '#f59e0b', low: '#22c55e'
  }

  // ── Counter demo ─────────────────────────────────────────────────────────
  let count = 0
  $: doubled  = count * 2
  $: isEven   = count % 2 === 0

  // ── Active tab ────────────────────────────────────────────────────────────
  type Tab = 'tasks' | 'reactive' | 'concepts'
  let activeTab: Tab = 'tasks'
</script>

<div class="app">
  <!-- Topbar -->
  <div class="topbar">
    <a href={portfolioUrl} class="back-link">← Portfolio</a>
    <div class="topbar-center">
      <span class="badge svelte">Svelte 4</span>
      <span class="badge stores">Stores</span>
      <span class="badge transitions">Transitions</span>
    </div>
    <div style="width:100px" />
  </div>

  <div class="container">
    <div class="page-header">
      <h1 class="page-title">Svelte Demo</h1>
      <p class="page-subtitle">
        Svelte compiles to vanilla JS — no virtual DOM, no runtime. Reactivity
        is built into the language itself with <code>$:</code> labels and stores.
      </p>
    </div>

    <div class="tabs">
      {#each ([['tasks','Task Board'],['reactive','Reactive ($:)'],['concepts','Key Concepts']] as [Tab, string][] as const) as [key, label]}
        <button class="tab" class:active={activeTab === key} on:click={() => activeTab = key}>
          {label}
        </button>
      {/each}
    </div>

    <!-- Task Board tab -->
    {#if activeTab === 'tasks'}
      <div class="panel" transition:fade={{ duration: 150 }}>
        <!-- Stats -->
        <div class="stats-row">
          <div class="stat">
            <div class="stat-num">{$stats.total}</div>
            <div class="stat-lbl">Total</div>
          </div>
          <div class="stat">
            <div class="stat-num done">{$stats.done}</div>
            <div class="stat-lbl">Done</div>
          </div>
          <div class="stat">
            <div class="stat-num active">{$stats.active}</div>
            <div class="stat-lbl">Active</div>
          </div>
          <div class="progress-wrap">
            <div class="progress-label">
              <span>Progress</span><span class="pct">{$stats.progress}%</span>
            </div>
            <div class="progress-track">
              <div class="progress-fill" style="width: {$stats.progress}%" />
            </div>
          </div>
        </div>

        <!-- Add + filter -->
        <div class="controls">
          <input bind:value={newTitle} class="inp" placeholder="New task..." on:keydown={e => e.key === 'Enter' && addTask()} />
          <button class="btn-add" on:click={addTask}>Add</button>
          <label class="toggle-label">
            <input type="checkbox" bind:checked={filterDone} />
            Active only
          </label>
        </div>

        <!-- Task list -->
        <div class="task-list">
          {#each filtered as task (task.id)}
            <div
              class="task-item"
              class:done={task.done}
              animate:flip={{ duration: 250 }}
              in:fly={{ y: -12, duration: 200 }}
              out:slide={{ duration: 180 }}
            >
              <div class="task-dot" style="background: {priorityColor[task.priority]}" />
              <span class="task-title">{task.title}</span>
              <button class="btn-toggle" on:click={() => toggle(task.id)}>
                {task.done ? '↩' : '✓'}
              </button>
              <button class="btn-del" on:click={() => remove(task.id)}>×</button>
            </div>
          {/each}
          {#if filtered.length === 0}
            <div class="empty" transition:fade>No tasks here</div>
          {/if}
        </div>
      </div>

    <!-- Reactive tab -->
    {:else if activeTab === 'reactive'}
      <div class="panel" transition:fade={{ duration: 150 }}>
        <div class="reactive-demo">
          <div class="counter-section">
            <div class="code-label">Reactive declarations with <code>$:</code></div>
            <pre class="code-block">let count = 0
$: doubled = count * 2
$: isEven  = count % 2 === 0</pre>

            <div class="counter-display">
              <button class="counter-btn" on:click={() => count--}>−</button>
              <div class="counter-value">{count}</div>
              <button class="counter-btn" on:click={() => count++}>+</button>
            </div>

            <div class="reactive-values">
              <div class="rv-row">
                <span class="rv-label">count</span>
                <span class="rv-value">{count}</span>
              </div>
              <div class="rv-row">
                <span class="rv-label">doubled</span>
                <span class="rv-value accent">{doubled}</span>
              </div>
              <div class="rv-row">
                <span class="rv-label">isEven</span>
                <span class="rv-value" class:green={isEven} class:red={!isEven}>{isEven}</span>
              </div>
            </div>
          </div>

          <div class="store-section">
            <div class="code-label">Derived store — auto-updates from <code>$tasks</code></div>
            <pre class="code-block">const stats = derived(tasks, $tasks => (&#123;
  total:    $tasks.length,
  done:     $tasks.filter(t => t.done).length,
  progress: Math.round(done / total * 100),
&#125;))</pre>
            <div class="reactive-values">
              <div class="rv-row"><span class="rv-label">$stats.total</span><span class="rv-value">{$stats.total}</span></div>
              <div class="rv-row"><span class="rv-label">$stats.done</span><span class="rv-value green">{$stats.done}</span></div>
              <div class="rv-row"><span class="rv-label">$stats.progress</span><span class="rv-value accent">{$stats.progress}%</span></div>
            </div>
            <p class="store-note">Change tasks in the "Task Board" tab — these update instantly.</p>
          </div>
        </div>
      </div>

    <!-- Concepts tab -->
    {:else if activeTab === 'concepts'}
      <div class="panel" transition:fade={{ duration: 150 }}>
        <div class="concepts-grid">
          {#each [
            { icon: '⚡', title: 'No virtual DOM', body: 'Svelte compiles your components to efficient imperative JS that directly updates the DOM.' },
            { icon: '🏪', title: 'Stores', body: 'writable(), readable(), and derived() give you reactive shared state without a framework.' },
            { icon: '💫', title: 'Transitions', body: 'Built-in fade, fly, slide, scale. No library needed — just import and use.' },
            { icon: '🎬', title: 'animate:flip()', body: 'Svelte animates list reordering automatically — just add animate:flip to the element.' },
            { icon: '$:', title: 'Reactive labels', body: '$: doubled = count * 2 — re-runs whenever count changes. Like computed, but simpler.' },
            { icon: '📦', title: 'Tiny bundle', body: 'No runtime shipped. A Svelte app is just compiled JS. This demo is under 30 kB gzipped.' },
          ] as concept}
            <div class="concept-card">
              <div class="concept-icon">{concept.icon}</div>
              <div class="concept-title">{concept.title}</div>
              <div class="concept-body">{concept.body}</div>
            </div>
          {/each}
        </div>
      </div>
    {/if}
  </div>
</div>

<style>
  :global(*, *::before, *::after) { box-sizing: border-box; margin: 0; padding: 0; }
  :global(html, body) { background: #060610; color: #e2e8f0; font-family: 'Inter', sans-serif; min-height: 100vh; }

  .app { min-height: 100vh; }

  .topbar { background: rgba(6,6,16,.95); backdrop-filter: blur(12px); border-bottom: 1px solid rgba(255,255,255,.06); padding: 12px 24px; display: flex; align-items: center; justify-content: space-between; position: sticky; top: 0; z-index: 100; }
  .back-link { font-size: 13px; color: #64748b; text-decoration: none; font-weight: 500; }
  .back-link:hover { color: #e2e8f0; }
  .topbar-center { display: flex; gap: 6px; }
  .badge { padding: 4px 10px; border-radius: 6px; font-size: 12px; font-weight: 600; }
  .badge.svelte { background: rgba(255,62,0,.12); border: 1px solid rgba(255,62,0,.3); color: #ff6b35; }
  .badge.stores { background: rgba(99,102,241,.1); border: 1px solid rgba(99,102,241,.25); color: #818cf8; }
  .badge.transitions { background: rgba(34,197,94,.1); border: 1px solid rgba(34,197,94,.25); color: #22c55e; }

  .container { max-width: 900px; margin: 0 auto; padding: 40px 24px 80px; }
  .page-header { margin-bottom: 32px; }
  .page-title { font-size: 30px; font-weight: 800; letter-spacing: -.03em; margin-bottom: 10px; }
  .page-subtitle { font-size: 15px; color: #64748b; line-height: 1.6; max-width: 560px; }
  .page-subtitle code { font-family: 'JetBrains Mono', monospace; color: #818cf8; background: rgba(99,102,241,.08); border-radius: 4px; padding: 1px 6px; }

  .tabs { display: flex; gap: 6px; margin-bottom: 20px; flex-wrap: wrap; }
  .tab { padding: 8px 18px; border-radius: 8px; font-size: 13px; font-weight: 500; background: transparent; border: 1px solid rgba(255,255,255,.06); color: #64748b; cursor: pointer; font-family: inherit; transition: all .15s; }
  .tab:hover { color: #e2e8f0; }
  .tab.active { background: rgba(255,62,0,.1); border-color: rgba(255,62,0,.3); color: #ff6b35; }

  .panel { background: #0a0a18; border: 1px solid rgba(255,255,255,.05); border-radius: 14px; padding: 28px; display: flex; flex-direction: column; gap: 20px; }

  /* Stats */
  .stats-row { display: flex; align-items: center; gap: 24px; flex-wrap: wrap; }
  .stat { display: flex; flex-direction: column; align-items: center; gap: 2px; }
  .stat-num { font-size: 28px; font-weight: 800; letter-spacing: -.02em; color: #94a3b8; }
  .stat-num.done { color: #22c55e; }
  .stat-num.active { color: #f59e0b; }
  .stat-lbl { font-size: 11px; color: #475569; text-transform: uppercase; letter-spacing: .07em; }
  .progress-wrap { flex: 1; min-width: 140px; }
  .progress-label { display: flex; justify-content: space-between; font-size: 12px; color: #64748b; margin-bottom: 6px; }
  .pct { color: #22c55e; font-weight: 600; }
  .progress-track { height: 4px; background: rgba(255,255,255,.06); border-radius: 2px; overflow: hidden; }
  .progress-fill { height: 100%; background: linear-gradient(90deg, #22c55e, #16a34a); border-radius: 2px; transition: width .5s ease; }

  /* Controls */
  .controls { display: flex; gap: 8px; align-items: center; flex-wrap: wrap; }
  .inp { flex: 1; min-width: 180px; background: rgba(255,255,255,.03); border: 1px solid rgba(255,255,255,.08); border-radius: 8px; padding: 9px 13px; font-size: 13px; color: #e2e8f0; font-family: inherit; outline: none; transition: border-color .15s; }
  .inp:focus { border-color: rgba(255,62,0,.4); }
  .btn-add { padding: 9px 18px; border-radius: 8px; background: rgba(255,62,0,.15); border: 1px solid rgba(255,62,0,.3); color: #ff6b35; font-size: 13px; font-weight: 600; cursor: pointer; font-family: inherit; transition: all .15s; }
  .btn-add:hover { background: rgba(255,62,0,.25); }
  .toggle-label { display: flex; align-items: center; gap: 6px; font-size: 13px; color: #64748b; cursor: pointer; }
  .toggle-label input { accent-color: #ff6b35; }

  /* Task list */
  .task-list { display: flex; flex-direction: column; gap: 6px; }
  .task-item { display: flex; align-items: center; gap: 10px; background: #0d0d1a; border: 1px solid rgba(255,255,255,.06); border-radius: 9px; padding: 12px 14px; transition: background .15s; }
  .task-item.done .task-title { text-decoration: line-through; color: #475569; }
  .task-dot { width: 8px; height: 8px; border-radius: 50%; flex-shrink: 0; }
  .task-title { flex: 1; font-size: 14px; color: #94a3b8; }
  .btn-toggle, .btn-del { background: none; border: none; cursor: pointer; font-size: 15px; padding: 2px 6px; border-radius: 5px; transition: all .15s; }
  .btn-toggle { color: #64748b; }
  .btn-toggle:hover { color: #22c55e; background: rgba(34,197,94,.08); }
  .btn-del { color: #334155; }
  .btn-del:hover { color: #ef4444; background: rgba(239,68,68,.08); }
  .empty { text-align: center; color: #334155; font-size: 13px; padding: 24px; }

  /* Reactive tab */
  .reactive-demo { display: grid; grid-template-columns: 1fr 1fr; gap: 24px; }
  .code-label { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: .08em; color: #475569; margin-bottom: 10px; }
  .code-label code { font-family: 'JetBrains Mono', monospace; color: #ff6b35; background: rgba(255,62,0,.08); border-radius: 4px; padding: 1px 5px; }
  .code-block { font-family: 'JetBrains Mono', monospace; font-size: 12px; line-height: 1.65; color: #94a3b8; background: #060610; border: 1px solid rgba(255,255,255,.05); border-radius: 8px; padding: 14px; white-space: pre; margin-bottom: 16px; }
  .counter-display { display: flex; align-items: center; gap: 20px; justify-content: center; margin: 20px 0; }
  .counter-btn { width: 40px; height: 40px; border-radius: 8px; background: rgba(255,62,0,.12); border: 1px solid rgba(255,62,0,.25); color: #ff6b35; font-size: 20px; cursor: pointer; display: flex; align-items: center; justify-content: center; transition: all .15s; }
  .counter-btn:hover { background: rgba(255,62,0,.22); }
  .counter-value { font-size: 48px; font-weight: 800; letter-spacing: -.03em; color: #e2e8f0; min-width: 80px; text-align: center; }
  .reactive-values { display: flex; flex-direction: column; gap: 8px; }
  .rv-row { display: flex; align-items: center; justify-content: space-between; background: #060610; border: 1px solid rgba(255,255,255,.05); border-radius: 7px; padding: 8px 12px; }
  .rv-label { font-family: 'JetBrains Mono', monospace; font-size: 12px; color: #64748b; }
  .rv-value { font-family: 'JetBrains Mono', monospace; font-size: 13px; font-weight: 600; color: #94a3b8; }
  .rv-value.accent { color: #818cf8; }
  .rv-value.green { color: #22c55e; }
  .rv-value.red { color: #ef4444; }
  .store-note { font-size: 12px; color: #475569; margin-top: 12px; line-height: 1.5; }

  /* Concepts tab */
  .concepts-grid { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 14px; }
  .concept-card { background: #0d0d1a; border: 1px solid rgba(255,255,255,.06); border-radius: 10px; padding: 18px; display: flex; flex-direction: column; gap: 8px; }
  .concept-icon { font-size: 20px; font-weight: 700; color: #ff6b35; font-family: 'JetBrains Mono', monospace; }
  .concept-title { font-size: 14px; font-weight: 700; color: #e2e8f0; }
  .concept-body { font-size: 12px; color: #64748b; line-height: 1.6; }

  @media (max-width: 680px) {
    .reactive-demo { grid-template-columns: 1fr; }
    .concepts-grid { grid-template-columns: 1fr 1fr; }
  }
</style>
